export const CONNECTION_CHECK_TIMEOUT_MS = 8000;
export const CONNECTION_CHECK_RETRIES = 1;
export const SUPPORTED_CRYPTO_REFRESH_MS = 24 * 60 * 60 * 1000;
export const BACKEND_GET_CACHE_TTL_MS = 750;
